name: CI/CD Pipeline
on:
  push:
    branches:
      - master  # Or 'main' depending on your setup

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    # Step to log into Azure using Service Principal (using the GitHub secrets)
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}  # Service Principal Client ID
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}  # Service Principal Client Secret
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}  # Tenant ID
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Azure Subscription ID
        environment: azurecloud  # Or other environment if you're not on Azure public cloud

    # Step to log in to Azure Container Registry (ACR)
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: k8steamcontainerregistry.azurecr.io

    # Build and Push Docker Image to ACR
    - name: Build and push Docker image
      run: |
        docker build -t k8steamcontainerregistry.azurecr.io/my-web-app:v1 .
        docker push k8steamcontainerregistry.azurecr.io/my-web-app:v1

    # Deploy to Azure Kubernetes Service (AKS)
    - name: Deploy to Azure Kubernetes Service
      run: |
        kubectl apply -f k8s/deployment.yaml  # Update to your actual Kubernetes manifest
