name: CI/CD Pipeline

on:
  push:
    branches:
      - master

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out code from the repository
    - name: Check out code
      uses: actions/checkout@v2

    # Step 2: Debug Azure Secrets to check if they're loaded correctly
    - name: Debug Azure Secrets
      run: |
        echo "Azure ACR Name: ${{ secrets.AZURE_ACR_NAME }}"  # Checking ACR Name
        echo "Azure ACR Username: ${{ secrets.AZURE_ACR_USERNAME }}"  # Checking ACR Username
        echo "Azure ACR Password: ${AZURE_ACR_PASSWORD}"  # Don't print password, just ensure it's available
        echo "Azure Credentials: ${{ secrets.AZURE_CREDENTIALS }}"  # Checking if AZURE_CREDENTIALS is loaded

    # Step 3: Log in to Azure using Service Principal (with GitHub secrets)
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: azurecloud

    # Step 4: Log in to Azure Container Registry (ACR)
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    # Step 5: Debug the ACR Name during Docker build step
    - name: Debug ACR Name during Docker build
      run: |
        echo "ACR Name: '${{ secrets.AZURE_ACR_NAME }}'"  # Debug the value of ACR Name before using it in the tag
        docker build -t ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/my-web-app:v1 .
        docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/my-web-app:v1

    # Step 6: Deploy to Azure Kubernetes Service (AKS)
    - name: Deploy to Azure Kubernetes Service
      run: |
        kubectl apply -f k8s/deployment.yaml  # Update this to your actual Kubernetes manifest file (deployment.yaml)
